### ISSUE TITLE
Add accounts and lessons to track progress

### ISSUE THREAD

**Issue by SmashedFrenzy16** [chesslablab/react-chess#529]
This could be a more long term effort, but adding accounts to ChesslaBlab could help track progress for users and make playing friends easier (by adding other user's accounts to your friends lists). Also, adding lessons could help a player see where they are at in chess, and adding their progress into accounts is a good way to track how good they are doing. We can make it so that only the player can see their stats, and can snooze who else could see them.

**Comment by SmashedFrenzy16** [comment]
In the last sentence, I meant choose (snooze was autocorrect - GitHub won't allow me to edit my first message in the issue right now).

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Unfortunately your idea does not fit the purpose of chesslablab,

"Chesslablab allows to learn and play chess online without being tracked. This is made possible because it does not use cookies of any sort and does not store information as other apps do, not even nicknames or chess games."

Therefore, storing any stats, even for the player himself would defeat the purpose and make the platform too similar to the likes of chess.com or lichess.org.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, chesslaBlab does not have to track your data in your account. It could only be viewable by the user and whoever they choose to see their data.

**Comment by SmashedFrenzy16** [comment]
I did take into fact chesslaBlab policies, so it's up to @programarivm to decide whether it's still viable. I would understand why it might not be, but I thought accounts would have been a nice feature.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 Unfortunately your idea does not fit the purpose of chesslablab,

"Chesslablab allows to learn and play chess online without being tracked. This is made possible because it does not use cookies of any sort and does not store information as other apps do, not even nicknames or chess games."

Therefore, storing any stats, even for the player himself would defeat the purpose and make the platform too similar to the likes of chess.com or lichess.org.

**Comment by programarivm** [comment]
Thanks @SmashedFrenzy16 for raising this issue!

This one is still perhaps too generic, what about raising a discussion instead? In my opinion, a chess expert should add the lessons, hopefully a titled FIDE player. Alternatively chess books in the public domain can be added to help users improve their chess skills.

Chess books in the public domain:

- [Chess Strategy by Edward Lasker](https://www.gutenberg.org/ebooks/5614)
- [Chess Fundamentals by José Raúl Capablanca](https://www.gutenberg.org/ebooks/33870)

Right now the link below is the closest thing to adding lessons in more specific terms.

- https://github.com/chesslablab/chess-api/issues/73

Keep it up,

**Comment by programarivm** [comment]
With regards to tracking users' games in order to display stats, I think it should be done in a way that respects privacy. What about something similar to a blockchain called chesschain?

Happy learning!

**Comment by CodeMaster7000** [comment]
A chesschain is a very nice idea - maybe @SmashedFrenzy16 can work on it.

**Comment by SmashedFrenzy16** [comment]
Hi there, happy learning and coding! @programarivm, I am interested in working on the blockchain based account system, and it has a potential to do well!

**Comment by programarivm** [comment]
See https://github.com/orgs/chesslablab/discussions/349
