### ISSUE TITLE
WSS connection is not being established

### ISSUE THREAD

**Issue by Mayank2001kh** [chesslablab/react-chess#563]
I tried implementing whole code on a website but its not able to connect WSS connection and shwing below issue

Ws.js:16 WebSocket connection to 'wss://3.110.165.76:3000/' failed: 
(anonymous) @ Ws.js:16
(anonymous) @ Ws.js:15
(anonymous) @ index.js:16
(anonymous) @ immutableStateInvariantMiddleware.ts:264
(anonymous) @ VariantBoard.js:17
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
localhost/:1 Uncaught (in promise) Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 0, …}

**Comment by programarivm** [comment]
@Mayank2001kh did you create an SSL certificate in the `ssl` folder?

As pointed out in [this discussion](https://github.com/orgs/chesslablab/discussions/350) since there is no staging server set up, a ChesslaBlab environment requires at least two repos up and running: [React Chess](https://github.com/chesslablab/react-chess) and [PHP Chess Server](https://github.com/chesslablab/chess-server).

Keep it up, and happy coding and learning!

**Comment by programarivm** [comment]
How is your `.env` set up?

```
HOST=www.chesslablab.com
HTTPS=true
PORT=9443

REACT_APP_API_HOST=pchess.net
REACT_APP_API_PORT=443

REACT_APP_WS_HOST=pchess.net
REACT_APP_WS_PORT=8443
```

**Comment by Mayank2001kh** [comment]
its same as follows. just to try it on my own chess sever i change 
REACT_APP_WS_HOST=pchess.net
REACT_APP_WS_PORT=8443
this two with my hosted server's ip and port

**Comment by programarivm** [comment]
Looks okay. 

Well, in this case I would add the following two entries to my `/etc/hosts`.

```
127.0.0.1       pchess.net 
127.0.0.1       www.chesslablab.com
```

This is to overcome this network error message.

```
npm start

> react-chess@1.2.20 start
> react-scripts start

Attempting to bind to HOST environment variable: www.chesslablab.com
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://cra.link/advanced-config

Could not find an open port at www.chesslablab.com.
Network error message: listen EADDRNOTAVAIL: address not available 18.154.41.60
```

**Comment by Mayank2001kh** [comment]
sir actually backend code is hosted on ec2 instance with pm2 configuration and i can connect that with postman but react frontend side is not able to connect can you join in meet to solve this issue?

**Comment by programarivm** [comment]
This looks to me like a different set up, not a localhost one for development purposes.

It may well be the case that your Postman is actually connecting to the actual `pchess.net` which is hosted on `3.121.169.246`. If so, make sure to update your `.env` as it is described next.

```
3.110.165.76       foobar.com 
```

In this example `foobar.com` is your own FQDN hostname rather than `pchess.net`.

I hope this will help.

**Comment by programarivm** [comment]
Also, make sure to update the `.env` of your PHP chess server accordingly.

```
BASE_URL=foobar.com 

JWT_ISS=foobar.com 
JWT_SECRET=password

UID=1000
GID=1000
```

**Comment by programarivm** [comment]
BTW @Mayank2001kh  port `8443` is actually hardcoded in [chess-server/cli/wss-server.php](https://github.com/chesslablab/chess-server/blob/master/cli/wss-server.php).

```php
<?php

namespace ChessServer;

use ChessServer\Socket;
use Ratchet\Http\HttpServer;
use Ratchet\Http\OriginCheck;
use Ratchet\Server\IoServer;
use Ratchet\WebSocket\WsServer;
use React\EventLoop\Factory;
use React\Socket\LimitingServer;
use React\Socket\Server;
use React\Socket\SecureServer;

require __DIR__  . '/../vendor/autoload.php';

$allowed = [
    'www.chesslablab.com',
];

$loop = Factory::create();

$server = new Server('0.0.0.0:8443', $loop);

$secureServer = new SecureServer($server, $loop, [
    'local_cert'  => __DIR__  . '/../ssl/certificate.crt',
    'local_pk' => __DIR__  . '/../ssl/private.key',
    'verify_peer' => false,
]);

$limitingServer = new LimitingServer($secureServer, 50);

$httpServer = new HttpServer(
    new OriginCheck(
      new WsServer(
          new Socket()
      ),
      $allowed,
    )
);

$ioServer = new IoServer($httpServer, $limitingServer, $loop);

$ioServer->run();
```

**Comment by Mayank2001kh** [comment]
yes i know that's hardcoded and even it checks from where the request is comming from in fucntion origincheck i removed that too and my backend is up and running as well as responding perfectly seperately but its not responding with react frontend

**Comment by programarivm** [comment]
Are you running the React app locally or on AWS? 

If locally, make sure to comment out the following entry in your `/etc/hosts` file so that the connection is established with the EC2 instance on AWS.

```
# 3.110.165.76       foobar.com 
``` 

Run the React app locally with `npm start`. 

Then, open a DevTools console and run the following JavaScript.

```js
const ws = new WebSocket('wss://pchess.net:8443');
ws.send('/start classical fen');
```

The chess server should respond accordingly. 

![Screenshot 2023-08-31 11:31:41](https://github.com/chesslablab/react-chess/assets/4062000/b205f055-5e5a-44df-ad48-5e143aa6db6a)

Otherwise it looks like you're probably trying to deploy the React app on AWS?

**Comment by Mayank2001kh** [comment]
![image](https://github.com/chesslablab/react-chess/assets/72145584/f8154f4d-25c7-4dce-a7e3-f8541ad42037)
![image](https://github.com/chesslablab/react-chess/assets/72145584/5b107ce8-6b95-4a6f-ba2d-4188557e473b)
 
and if you can see both the server are responding to postman

**Comment by programarivm** [comment]
Thanks for sharing the screenshots!

See:

- https://github.com/chesslablab/chess-server/issues/135

It'd be also helpful if you could share a DevTools screenshot.

**Comment by programarivm** [comment]
@Mayank2001kh probably the easiest thing to do is buy an SSL certificate for your FQDN hostname. 

Otherwise, if self-signed, you may need to first approve the certificate.

See:

- [Secure websockets with self-signed certificate](https://stackoverflow.com/questions/5312311/secure-websockets-with-self-signed-certificate#:~:text=To%20approve%20the%20certificate%20you,the%20opportunity%20to%20approve%20it.)

Keep it up,

**Comment by Mayank2001kh** [comment]
![image](https://github.com/chesslablab/react-chess/assets/72145584/5b104d28-5558-4bc3-aa40-77ef920585f6)
that what i am getting i have proper SSL as well

**Comment by programarivm** [comment]
It looks like iterating to the previous step:

- https://github.com/chesslablab/react-chess/issues/563#issuecomment-1700730052

Open a DevTools console and run the following JavaScript.

```
const ws = new WebSocket('wss://foobar.com:8443');
ws.send('/start classical fen');
```

The chess server should respond accordingly with a message.

**Comment by Mayank2001kh** [comment]
![image](https://github.com/chesslablab/react-chess/assets/72145584/db303dca-b53a-41a1-b742-e118604b5fcc)
That what i am getting

**Comment by programarivm** [comment]
If the SSL certificate is properly set up, I'm not quite sure why the connection with the wss server is established using the localhost IP address. A FQDN hostname should be used instead as described in the example:

```
const ws = new WebSocket('wss://foobar.com:8443');
ws.send('/start classical fen');
```

**Comment by Mayank2001kh** [comment]
i am tring both localhost as well as aws server ip address both are not working. i have hosted backend on both the ways on local as well and AWS EC2 as well

![image](https://github.com/chesslablab/react-chess/assets/72145584/6f438ea7-1ad1-48da-b0b7-7a4be09316c4)


can you try to connect to the provided IP?

**Comment by programarivm** [comment]
Sorry that I still can't connect to the WebSocket server for some reason.
 
Let's recap, this looks like an SSL issue. The easiest thing to do is buy a trusted SSL certificate. It is preferable to connect to the WebSocket server using a FQDN like `foobar.com` on port number `8443` rather than on port `3000`.

```
const ws = new WebSocket('wss://foobar.com:8443');
ws.send('/start classical fen');
```
This is how the chess server is currently running on `pchess.net`.

Also you may want to debug the connection with the help of [websocat](https://github.com/vi/websocat).

These bugs need to be fixed for the chess server to be easily deployed on AWS:

- https://github.com/chesslablab/chess-server/issues/132
- https://github.com/chesslablab/chess-server/issues/135


Thank you so much for pointing those out.

Keep it up, and happy learning and coding!

**Comment by Mayank2001kh** [comment]
i tried changing SSL certificate as well worked with .env for port and also worked for allowed website that's  not the issue. i think i am getting issue in frontend side as i can connect it with postman server and communicate with it as well as you can see in below image
![image](https://github.com/chesslablab/react-chess/assets/72145584/82ccdcbf-39a8-413e-9b16-55199889edb2)

But considering it's hosting issue i tried it using on localhost as well that's not working as well.

I don't know what's and where's the issue?

**Comment by Mayank2001kh** [comment]
@programarivm can you guide me with this?

**Comment by Mayank2001kh** [comment]
It was SSL Certificate issue so i removed SSL and connected it with unsecured network
