### ISSUE TITLE
Error in project

### ISSUE THREAD

**Issue by zakiyousufi** [chesslablab/react-chess#656]
When I ran the Project I got some errors on the console 

<img width="960" alt="errorr" src="https://github.com/chesslablab/react-chess/assets/87229464/deab27b3-78e7-43fe-867d-2899549f12da">

The error message suggests that there is an issue with constructing a WebSocket connection in the code. The URL 'wss://undefined:undefined' is being passed to the WebSocket constructor, which is invalid.

**Comment by programarivm** [comment]
Thank you @zakiyousufi for asking this question!

The app should be accessed through this URL.

```
https://www.chesslablab.com:9443/
```

These are the default settings defined in the `.env.example` file.

```
HOST=www.chesslablab.com
HTTPS=true
PORT=9443

REACT_APP_API_HOST=pchess.net
REACT_APP_API_PORT=443

REACT_APP_WS_HOST=pchess.net
REACT_APP_WS_PORT=8443
```

![figure_01](https://github.com/chesslablab/react-chess/assets/4062000/cab73bc8-19ce-4cd6-85a0-95e89640a308)

BTW, did you try to add the following entry to your `/etc/hosts` file?

```
127.0.0.1       www.chesslablab.com
```

Happy coding!

**Comment by BreakTos** [comment]
Hii , I tried doing the steps you gave above and i seem to have done all of those
My etc/hosts
![image](https://github.com/chesslablab/react-chess/assets/76687690/4a569b61-6bd2-47cd-adfa-3367ef15daff)
My env.example
![image](https://github.com/chesslablab/react-chess/assets/76687690/cca8cee4-da08-44c4-82b0-067afedaa734)
On trying to access 9443 port
![image](https://github.com/chesslablab/react-chess/assets/76687690/38b1b8b2-46d5-4e1b-a2d4-d7f4eb1772e0)

I forked and git cloned this repo, did npm install . and it automatically opened localhost:3000 which couldn't establish connection after npm start . 
I didn't do this step (cp .env.example .env) because i couldnt understand what it is and is it windows or linux command

**Comment by programarivm** [comment]
`npm start` should automatically open `https://www.chesslablab.com:9443`

**Comment by BreakTos** [comment]
That is not happening , npm start is opening localhost 3000


![image](https://github.com/chesslablab/react-chess/assets/76687690/82afef44-5e7c-4da6-8917-d835452c4df1)
