### ISSUE TITLE
Custom chat URL in the environment settings

### ISSUE THREAD

**Issue by d47081** [chesslablab/react-chess#687]
I want to connect another chat room URL in my localnet project, but `https://web.libera.chat/gamja/#chesslablab` hardcoded in `src/App.js`

So what about custom option in `.env`?

Or maybe some advice how to include environment value as not familiar with react.js
Thanks

**Comment by programarivm** [comment]
Thank you @d47081 for contributing to this repo!

Let me check out this PR and get back to you with an update ASAP. At this moment, I am focusing on the PHP side of things working on [chesslablab/coach](https://github.com/chesslablab/coach).

[chesslablab/react-chess](https://github.com/chesslablab/react-chess) has been available at chesslablab.com for several months. It was costing about $80 per month on AWS mainly because of the huge database containing more than one million chess games!

The thing is, it was not profitable and was recently shutdown. The ChesslaBlab community is still at an early stage of growth and one of the problems we found is that indexing the content is not too obvious.

See:

- [What is true in the following statement?](https://twitter.com/programarivm/status/1727396105888133305)

React and Redux are both great for frontend development but there are just so few users playing chess with React Chess. Any ideas on growing the community or making it profitable?

Happy coding and learning!

**Comment by programarivm** [comment]
Well, until recently it was somewhat easier to keep on developing the app because there was a staging server on that domain. A significant part of the cost was because of the database.
